### ISSUE TITLE
about swinunetr and unetr

### ISSUE THREAD

**Issue by smanman** [Amshaker/unetr_plus_plus#49]
I'm bothering you! I want to ask you when you ran the comparison model swinutr and unetr, did you directly change the Jiang network architecture to the comparative model architecture directly on the basis of your code? Or is it an experiment against the original code of the model? I followed the first method, but it was reported an error, it was not solved, I want to ask if you know how to solve it? Are you getting such an error?
Traceback (most recent call last):
  File "/home/code/unetr_pp++/unetr_pp/run/run_training.py", line 171, in <module>
    main()
  File "/home/code/unetr_pp++/unetr_pp/run/run_training.py", line 142, in main
    trainer.initialize(not validation_only)
  File "/home/code/unetr_pp++/unetr_pp/training/network_training/unetr_pp_trainer_tumor.py", line 156, in initialize
    assert isinstance(self.network, (SegmentationNetwork, nn.DataParallel))
AssertionError

Process finished with exit code 1
We kindly ask for your prompt reply

**Comment by AustinYuAo** [comment]
Hi , I had the same problem, did you solve it?

**Comment by 6018203135** [comment]
@AustinYuAo no

**Comment by 6018203135** [comment]
@Amshaker excuse me? help me,thanks

**Comment by Amshaker** [comment]
UNETR and SwinUNETR are integrated into UNETR++. It will not work as it, and requires some engineering hands-on. It requires some modification in the network architecture to be adapted. For instance, the original architecture of UNETR has an input of 96x96x96. You need to do network modification to adapt with 64x128x128.

**Comment by AustinYuAo** [comment]
This problem requires you to change your code to class UNETR(SegmentationNetwork): replaces the original class UNETR(nn.Module). 
You will find it works.
