### ISSUE TITLE
Task003_tumor dataset cannot be trained?

### ISSUE THREAD

**Issue by liaochuanlin** [Amshaker/unetr_plus_plus#55]
I am using data from this folder:  ../DATASET_Tumor/unetr_pp_raw/unetr_pp_raw_data/Task03_tumor/Task003_tumor/nnFormerData_plans_v2.1
###############################################
self.crop_size in init train: [128 128 128]
[0.57142857 0.28571429 0.14285714]
loading dataset
loading all case properties
2023-09-15 15:03:28.663895: Using splits from existing split file: ../DATASET_Tumor/unetr_pp_raw/unetr_pp_raw_data/Task03_tumor/Task003_tumor/splits_final.pkl
2023-09-15 15:03:28.664275: The split file contains 5 splits.
2023-09-15 15:03:28.664320: Desired fold for training: 0
2023-09-15 15:03:28.664411: This split has 387 training and 73 validation cases.
unpacking dataset
done
Traceback (most recent call last):
  File "../unetr_pp/run/run_training.py", line 171, in <module>
    main()
  File "../unetr_pp/run/run_training.py", line 142, in main
    trainer.initialize(not validation_only)
  File "/home/lcl/unetr_plus_plus/unetr_pp/training/network_training/unetr_pp_trainer_tumor.py", line 150, in initialize
    self.initialize_network()
  File "/home/lcl/unetr_plus_plus/unetr_pp/training/network_training/unetr_pp_trainer_tumor.py", line 189, in initialize_network
    model_flops = flops.total()
  File "/home/lcl/anaconda3/envs/unetr_pp/lib/python3.8/site-packages/fvcore/nn/jit_analysis.py", line 248, in total
    stats = self._analyze()
  File "/home/lcl/anaconda3/envs/unetr_pp/lib/python3.8/site-packages/fvcore/nn/jit_analysis.py", line 583, in _analyze
    op_counts = self._op_handles[kind](inputs, outputs)
  File "/home/lcl/anaconda3/envs/unetr_pp/lib/python3.8/site-packages/fvcore/nn/jit_handles.py", line 181, in einsum_flop_jit
    assert len(inputs) == 2, len(inputs)
AssertionError: 3

**Comment by Holloworker** [comment]
Hi, I met the same problem. Did you solve it?

**Comment by Amshaker** [comment]
Could you please share the command you use for running?
It seems there is an issue in the input shape for measuring the FLOPs. Is the training working when you comment measuring the FLOPs?

**Comment by holawx** [comment]
maybe the version of fvcore is old. you can try to update it to the newest version which solved my problem.
