### ISSUE TITLE
Do you still have problems with your own trained pickle files?

### ISSUE THREAD

**Issue by liaochuanlin** [Amshaker/unetr_plus_plus#59]
using the following model files:  ['/home/lcl/unetr_plus_plus/unetr_pp/evaluation/unetr_pp_tumor_checkpoint/unetr_pp/3d_fullres/Task003_tumor/unetr_pp_trainer_tumor__unetr_pp_Plansv2.1/fold_0/model_final_checkpoint.model']
starting preprocessing generator
starting prediction...
Traceback (most recent call last):
  File "/home/lcl/unetr_plus_plus/unetr_pp/inference/predict_simple.py", line 245, in <module>
    main()
  File "/home/lcl/unetr_plus_plus/unetr_pp/inference/predict_simple.py", line 237, in main
    predict_from_folder(model_folder_name, input_folder, output_folder, folds, save_npz, num_threads_preprocessing,
  File "/home/lcl/unetr_plus_plus/unetr_pp/inference/predict.py", line 633, in predict_from_folder
    return predict_cases(model, list_of_lists[part_id::num_parts], output_files[part_id::num_parts], folds,
  File "/home/lcl/unetr_plus_plus/unetr_pp/inference/predict.py", line 206, in predict_cases
    for preprocessed in preprocessing:
  File "/home/lcl/unetr_plus_plus/unetr_pp/inference/predict.py", line 102, in preprocess_multithreaded
    assert isinstance(trainer, Trainer_acdc) or isinstance(trainer, Trainer_synapse)
AssertionError

**Comment by shenggebiya** [comment]
I'm also having this issue
